[version]
current = "0.3.0-beta"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (?P<extra>.*)
'''

[git]
message_template = "bump: version {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "pyproject.toml"
search = 'version = "{current_version}"'

[[before_commit]]
name = "Check tests"
cmd = "uv run prek && uv run pytest"
